<?php
$message = "";
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $name = htmlspecialchars($_POST["name"]);
    $message = "Hello, <strong>" . $name . "</strong>! This message was generated by PHP.";
}
?>
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>PHP Basics - WebTech Gallery</title>
    <link rel="stylesheet" type="text/css" href="styles.css" />
</head>
<body>
    <div id="container">
        <h1>PHP Basics</h1>

        <p>PHP is a server-side scripting language used to create dynamic content. It processes on the server and generates XHTML or other output for the browser.</p>

        <h2>Example: Hello Form</h2>
        <form method="post" action="php.php">
            <label for="name">Enter your name:</label>
            <input type="text" name="name" id="name" />
            <input type="submit" value="Submit" />
        </form>

        <?php
        if (!empty($message)) {
            echo '<p>' . $message . '</p>';
        }
        ?>

        <h2>Basic PHP Syntax Example:</h2>
        <pre>
&lt;?php
$greeting = "Hello, world!";
echo $greeting;
?&gt;
        </pre>

        <p><a href="index.html">← Back to Home</a></p>

        <div id="footer">
            <p>&copy; 2025 WebTech Gallery | Summer Project</p>
        </div>
    </div>
</body>
</html>
